<?php

namespace Lara\Common\Database\Seeders;

use Illuminate\Database\Seeder;

class LaraLaraResourceEntityCustomFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_resource_entity_custom_fields')->delete();
        
        \DB::table('lara_resource_entity_custom_fields')->insert(array (
            0 => 
            array (
                'id' => 64,
                'entity_id' => 42,
                'title' => 'type',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'type',
                'field_name_temp' => NULL,
                'field_options' => '["image","caption","payoff"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            1 => 
            array (
                'id' => 65,
                'entity_id' => 42,
                'title' => 'captiontype',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'captiontype',
                'field_name_temp' => NULL,
                'field_options' => '["block","fade"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'captiontype',
                'rule_operator' => 'isequal',
                'rule_value' => 'caption',
                'sort_order' => 120,
            ),
            2 => 
            array (
                'id' => 66,
                'entity_id' => 42,
                'title' => 'subtitle',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'subtitle',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 130,
            ),
            3 => 
            array (
                'id' => 67,
                'entity_id' => 42,
                'title' => 'payoff',
                'field_hook' => 'after-last',
                'field_type' => 'richeditor',
                'field_name' => 'payoff',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 140,
            ),
            4 => 
            array (
                'id' => 68,
                'entity_id' => 42,
                'title' => 'url',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'url',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 150,
            ),
            5 => 
            array (
                'id' => 69,
                'entity_id' => 42,
                'title' => 'urltitle',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'urltitle',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 160,
            ),
            6 => 
            array (
                'id' => 70,
                'entity_id' => 42,
                'title' => 'urltext',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'urltext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 170,
            ),
            7 => 
            array (
                'id' => 71,
                'entity_id' => 42,
                'title' => 'overlaycolor',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaycolor',
                'field_name_temp' => NULL,
                'field_options' => '["black","white","brand1","brand2","brand3"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 180,
            ),
            8 => 
            array (
                'id' => 72,
                'entity_id' => 42,
                'title' => 'overlaytransp',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaytransp',
                'field_name_temp' => NULL,
                'field_options' => '["0","10","20","30","40","50","60","70","80","90"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 190,
            ),
            9 => 
            array (
                'id' => 73,
                'entity_id' => 42,
                'title' => 'overlaysize',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaysize',
                'field_name_temp' => NULL,
                'field_options' => '["full","block"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 200,
            ),
            10 => 
            array (
                'id' => 74,
                'entity_id' => 42,
                'title' => 'textposition',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'textposition',
                'field_name_temp' => NULL,
                'field_options' => '["center","left","right"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 210,
            ),
            11 => 
            array (
                'id' => 94,
                'entity_id' => 1,
                'title' => 'ishome',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'ishome',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'hidden',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            12 => 
            array (
                'id' => 95,
                'entity_id' => 1,
                'title' => 'menuroute',
                'field_hook' => 'before-title',
                'field_type' => 'string',
                'field_name' => 'menuroute',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 1,
                'rule_state' => 'hidden',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            13 => 
            array (
                'id' => 100,
                'entity_id' => 52,
                'title' => 'hook',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'hook',
                'field_name_temp' => NULL,
                'field_options' => '["content_top","content_bottom","home1","home2","home3","home4","home5","home6","home7","home8","home9","home10","footer1","footer2","footer3","footer4"]',
                'is_required' => 1,
                'is_filter' => 1,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            14 => 
            array (
                'id' => 101,
                'entity_id' => 52,
                'title' => 'type',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'type',
                'field_name_temp' => NULL,
                'field_options' => '["text","icon","feature","module"]',
                'is_required' => 1,
                'is_filter' => 1,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 130,
            ),
            15 => 
            array (
                'id' => 102,
                'entity_id' => 52,
                'title' => 'resource_slug',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'resource_slug',
                'field_name_temp' => NULL,
                'field_options' => '["get_entity_resources"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 131,
            ),
            16 => 
            array (
                'id' => 103,
                'entity_id' => 52,
                'title' => 'resource_term',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'resource_term',
                'field_name_temp' => NULL,
                'field_options' => '["get_entity_terms"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 132,
            ),
            17 => 
            array (
                'id' => 104,
                'entity_id' => 52,
                'title' => 'is_global',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'is_global',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 120,
            ),
            18 => 
            array (
                'id' => 105,
                'entity_id' => 52,
                'title' => 'image_required',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'image_required',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 133,
            ),
            19 => 
            array (
                'id' => 106,
                'entity_id' => 52,
                'title' => 'max_items',
                'field_hook' => 'after-title',
                'field_type' => 'number',
                'field_name' => 'max_items',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 134,
            ),
            20 => 
            array (
                'id' => 107,
                'entity_id' => 52,
                'title' => 'iconclass',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'iconclass',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'icon',
                'sort_order' => 141,
            ),
            21 => 
            array (
                'id' => 108,
                'entity_id' => 52,
                'title' => 'iconalign',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'iconalign',
                'field_name_temp' => NULL,
                'field_options' => '["top","left","right"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'icon',
                'sort_order' => 142,
            ),
            22 => 
            array (
                'id' => 109,
                'entity_id' => 52,
                'title' => 'linktext',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'linktext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isnotequal',
                'rule_value' => 'module',
                'sort_order' => 150,
            ),
            23 => 
            array (
                'id' => 110,
                'entity_id' => 52,
                'title' => 'linkurl',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'linkurl',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isnotequal',
                'rule_value' => 'module',
                'sort_order' => 155,
            ),
            24 => 
            array (
                'id' => 111,
                'entity_id' => 52,
                'title' => 'usecache',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'usecache',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 125,
            ),
            25 => 
            array (
                'id' => 112,
                'entity_id' => 52,
                'title' => 'sortorder',
                'field_hook' => 'after-title',
                'field_type' => 'number',
                'field_name' => 'sortorder',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 126,
            ),
            26 => 
            array (
                'id' => 113,
                'entity_id' => 52,
                'title' => 'template',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'template',
                'field_name_temp' => NULL,
                'field_options' => '["get_widget_templates"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 160,
            ),
            27 => 
            array (
                'id' => 114,
                'entity_id' => 59,
                'title' => 'linktext',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'linktext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            28 => 
            array (
                'id' => 115,
                'entity_id' => 59,
                'title' => 'linkurl',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'linkurl',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            29 => 
            array (
                'id' => 116,
                'entity_id' => 59,
                'title' => 'hook',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'hook',
                'field_name_temp' => NULL,
                'field_options' => '["contact","newsletter"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            30 => 
            array (
                'id' => 117,
                'entity_id' => 59,
                'title' => 'type',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'type',
                'field_name_temp' => NULL,
                'field_options' => '["solid","image","parallax"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            31 => 
            array (
                'id' => 118,
                'entity_id' => 59,
                'title' => 'overlaycolor',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaycolor',
                'field_name_temp' => NULL,
                'field_options' => '["black","brand"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            32 => 
            array (
                'id' => 119,
                'entity_id' => 59,
                'title' => 'overlaytransp',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaytransp',
                'field_name_temp' => NULL,
                'field_options' => '["0","10","20","30","40","50","60","70","80","90"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
        ));
        
        
    }
}